version: "3.8"
services:
  bot:
    build:
      context: "."
      dockerfile: "Dockerfile"
    environment:
      BOT_TOKEN: "${BOT_TOKEN}"
      LOG_LEVEL: "${LOG_LEVEL}"
      TEST_SERVERS: "${TEST_SERVERS}"
    deploy:
      restart_policy:
        condition: "unless-stopped"
